Add some other examples for symbol
HowProgrammingWorks/Symbol pull request #1
Opened 2018-03-03 18:41 UTC by Nicita01

2018-03-04 01:32 UTC, tshemsedinov requested changes
Тут все самостоятельно написано или что-то скопировано из интернетиков?

2018-03-04 01:32 UTC, tshemsedinov commented on JavaScript/5-iterator2.js
> +Number.prototype[Symbol.iterator] = function() {
Не думаю, что модификация базовых классов это хороший пример

2018-03-04 01:32 UTC, tshemsedinov commented on JavaScript/5-iterator2.js
> +
Вот эти 4 блока выше, если бы они были нужны, то их можно было бы оптимизировать сильно, к двум свести, а то и к одному

2018-03-04 20:36 UTC, Nicita01 commented
Вроде как самостоятельно. Разве что в интернете нашел отдалённую идею модификации Number. Ну и тоже отдалённо, почитал как изменять Symbol.toPrimitive

2018-03-05 09:52 UTC, tshemsedinov requested changes
В некоторых местах примеры нужно разделить на два блока кода:
- реализация (implementation)
- пример использования (usage example)

Я между ними ставлю `// Usage`

2018-03-05 09:52 UTC, tshemsedinov commented on JavaScript/7-hide-symbols-usage.js
> +const hideSymbol = require(__dirname + '/7-hide-symbols.js');
`require('./7-hide-symbols.js');`

2018-03-05 09:52 UTC, tshemsedinov commented on JavaScript/7-hide-symbols-usage.js
> +  name: 'Gena',
Че за гена? Где Марк Аврелий?

2018-03-05 09:53 UTC, tshemsedinov commented
И еще в некоторых местах есть 2 строки отступа, я так не делаю в примерах ни где, это ты имеешь в виду более сильное разделение или просто случайно?

2018-03-05 13:30 UTC, Nicita01 commented on JavaScript/7-hide-symbols-usage.js
> +  name: 'Gena',
Хах. Будет

2018-03-05 13:40 UTC, Nicita01 commented
Да, более сильное разделение хотел. Как бы выводы до проксирования, и после. Чтобы не запутаться

2018-03-05 14:41 UTC, tshemsedinov approved these changes

2018-03-05 14:41 UTC, merged